# 트리의 앙상블

<table align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/rickiepark/hg-mldl/blob/master/5-3.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />구글 코랩에서 실행하기</a>
  </td>
</table>

## 랜덤포레스트

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
# numpy, pandas, train_test_split import
wine = pd.read_csv('https://bit.ly/wine_csv_data')
# 데이터프레임화하여 wine에 저장
data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
# '알코올 도수', '당도', 'pH' 열을 data에 저장
target = wine['class'].to_numpy()
# 'clas'열을 target에 저장
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)
# 훈련 세트와 테스트 세트를 8:2 나눔

In [ ]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
# cross_validate, RandomForestClassifier 클래스 import

rf = RandomForestClassifier(n_jobs=-1, random_state=42)
# RandomForestClassifier 객체 rf를 생성
scores = cross_validate(rf, train_input, train_target, return_train_score=True, n_jobs=-1)
# cross_validate()에 rf, train_input, train_target을 인수로 전달
# return_train_score=True를 통해 검증 점수뿐만 아니라 훈련 세트에 대한 점수도 같이 반환

print(np.mean(scores['train_score']), np.mean(scores['test_score']))
# 훈련 세트와 테스트 세트 점수 출력

0.9973541965122431 0.8905151032797809


In [ ]:
rf.fit(train_input, train_target)
# rf를 훈련
print(rf.feature_importances_)
# 특성 중요도 출력

[0.23167441 0.50039841 0.26792718]


In [ ]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
# oob_score=True를 통해 부트스트랩 샘플에 포함되지 않고 남은 샘플로 결정 트리를 평가
rf.fit(train_input, train_target)
# rf를 훈련
print(rf.oob_score_)
# 각 결정 트리의 00B 점수를 평균내어 출력

0.8934000384837406


## 엑스트라트리

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
# ExtraTreesClassifier 클래스 import
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
# ExtraTreesClassifier의 객체 et를 생성
scores = cross_validate(et, train_input, train_target, return_train_score=True, n_jobs=-1)
# cross_validate()에 et, train_input, train_target을 인수로 전달
print(np.mean(scores['train_score']), np.mean(scores['test_score']))
# 훈련 세트와 테스트 세트 점수 출력

0.9974503966084433 0.8887848893166506


In [ ]:
et.fit(train_input, train_target)
print(et.feature_importances_)
# et의 특성 중요도 출력

[0.20183568 0.52242907 0.27573525]


## 그레이디언트 부스팅

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
# GradientBoostingClassifier 클래스 import
gb = GradientBoostingClassifier(random_state=42)
# GradientBoostingClassifier의 객체 gb 생성
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1)
# cross_validate()에 gb, train_input, train_target 인수로 전달
print(np.mean(scores['train_score']), np.mean(scores['test_score']))
# 훈련 셑트와 테스트 세트 점수 출력

0.8881086892152563 0.8720430147331015


In [ ]:
gb = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2, random_state=42)
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1)
# n_estimators=500로 하여 결정 트리 개수를 500으로 5배 늘림
print(np.mean(scores['train_score']), np.mean(scores['test_score']))
# 훈련 세트와 테스트 세트 점수 출력

0.9464595437171814 0.8780082549788999


In [ ]:
gb.fit(train_input, train_target)
print(gb.feature_importances_)
# gb의 특성 중요도 출력

[0.15872278 0.68010884 0.16116839]


## 히스토그램 기반 부스팅

#### XGBoost

In [ ]:
from xgboost import XGBClassifier
# XGBClassifier 클래스 import
xgb = XGBClassifier(tree_method='hist', random_state=42)
# XGBClassifier의 객체 xgb 생성
scores = cross_validate(xgb, train_input, train_target, return_train_score=True, n_jobs=-1)
# cross_validate()에 xgb, train_input, train_target을 인수로 전달
print(np.mean(scores['train_score']), np.mean(scores['test_score']))
# 훈련 세트, 테스트 세트 점수 출력

0.9558403027491312 0.8782000074035686


#### LightGBM

In [ ]:
from lightgbm import LGBMClassifier
# LGBMClassifier 클래스 import
lgb = LGBMClassifier(random_state=42)
# LGBMClassifier의 객체 lgb 생성
scores = cross_validate(lgb, train_input, train_target, return_train_score=True, n_jobs=-1)
# cross_validate()에 lgb, train_input, train_target을 인수로 전달
print(np.mean(scores['train_score']), np.mean(scores['test_score']))
# 훈련 세트, 테스트 세트 점수 출력

0.935828414851749 0.8801251203079884
